notifications:
  slack:
    secure: "aCGPqhzg6Uv5poK/FA+m8KF/tfdFWywt/2s4+rwKNT/a04rv2GC/5gNYhcpCFhcqrT+TAzD9BEz6opJ4E78Tu++Hg1LXJvNb7wIZV3aI144GnT912sepfuFBIl5xve7vbisuWB5GmjO6d4g7aS+X8Ks1yJp+l4QNmjahzFZ66w6cmgQHt3zlNhFyHuDi/wcM01AfRUraZFVKN0QcoOxx42f+Rk2ru0X61NGqPhhBFEJTON5eDZoh7gUjJHB9STaF3tq3gbLHCylBZ1ukf/f/r3AGSP4EMKV+IwfAhidBNeWR1C0a+8qUI0Z7xiMX0L5Fs2FuHDkRRHCTz22bMhqDaA+vfK187D9b+Ci2TEd42H+kyiidt/8rVMJo8LW8u5BA++Krbhph6FmyGY2vAm1074qNq6gTlDuVh+4Ml4b5+89nDCdRLA8HrARfOWiTcMdFYn3M6WSjXi59PlkzzDJ1YZBciXyFinjx15Ik57C6M0ex9S5FGBSIP9bwK5E8DR3KBroLdIOAxe/LXQyNe7TtyjfBI1eaaZXzfZuexbBrxRCNQMhJiJ8i8ZGslQN2+56KCAo8VktMT8OqJxK7nKXMFhJoFQQvBgBUOg62ar5DqZpweI174uAz5P0nu1WCqW6hz66kiwR2asRMwigfzT5rWRMzUtePWCWRp9oDLJ+BT1k="
  email: false
language: node_js
node_js:
  - '4'
env:
  secure: "oDPFsVAnmHZ/2ekR0KiKEtpGIEb8T/9pGpxBDpd2UonU1vX64QWssCAEjsmxlqbwnAqgq+YNABRt5Ox1DVvivwBGx6uPiwL9PZjokNamSUujy2JweQKg50h7QPy+g3spqi6vG0OhmFj/oUBRVzGDkyDD2+gwoeoY8pQUf6XmRJofP5dc/lsD4D+bIwF1UL9s9wWDK5yI/RDGVq1BFWhJzcnIJso9HVfxRr+BT2zdbTu731IhurYRRewhobMg5OdN6/e0Ei0TkZvPAyf/Um1cwM3P9cZ2YEqV6tEh2sqRuOqmlsCOhpwimpNh6tFKGwnLtOO+PD9mxPh2JF1neViAI3an429mWBOIDuZkHI0KUiXd8zLQsQgm4LtUVCuYgtt2CqbLXc5sV4hY7b2ibMXyjyToDLv/hMXuvCYe9O8rjZa1zAh2Y+ywjiICSIXYJ1/rehMxU/JDAxRNZ2719dGv+/I6Bo4+FhG65EW2FKMmLcRRljLojuTG7Huiy/X/y6n+82DNHOM92Pyi6YOR16X1VJwE4cdBglK0rE1nVSR5Qz4sL51Y+7VFbZyRZyhUPoDPJxpG4yzNwSnBWrE+pYhxzbrHWc1CzId/cl13vj8kO+ah/oNFg3FtPW8VBxkYyl7Nha67idpnjMwllx7X6uvliJg1IS+qE9M4MaVn/rz9MAE="
sudo: required
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"
addons:
  firefox: 49.0
before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
install:
  - npm install
  - bower install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm test
deploy:
  - provider: script
    script: ember deploy staging --activate=true
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: ember deploy production --activate=true
    skip_cleanup: true
    on:
      branch: master
