notifications:
  slack:
    secure: "SUEwzqBFA0Abcsovaxao8kzxm6Qr4l7S+N095eu6rdLnXi2watCfSk2GpQ5k2uyaM2JPH2yxnHrZmfYYKMnCV5yNHSYf2FyfiBYNvD61kRx4dWiiKHhGLJJGUuSW+/AjMrT6qLAnujSkb+24k84KyHveibgdAVci65VvD76zM2+58lUzkdglLk3+hLsOlYIk1rGxOPyb743hFoigbNjRKyFGuIHajxe5PDK2rueUjVRuiq5Tii1T5UCwu/I+uD5bDJKAFmvIgTiKwzTLra3G1q1DKr8bN/btpZ1YYf/6Yfge7+RYuw8l2nEkzfxPNQs0GomJljVobW/KCpQx1VhEWuqWrufdF0VEjjlxI4zg/7LMlmGmR3CFrsI/JABvDGk0s5znGZr2qihVj0FxeCKh62MCoaw4aAXcNUggaBGJbPE0sLFF8KsA6MYgcLJE5YpecRfRNvcrYwgfFNM6+cwp2C+uEWnMStKNjYGkBta8cl521uqG72ReM/YXG/VAygOcn30W22Jj9vd4F1i4AW0t2tON3M7KiWm4rbAmHOopv78HYjPf3n61k066Su6fX1AuSOgXkvmjrL4oWuBbD83x+VNKMuLLx7O8+L2YOpnbeD85/c9NwVvaGDZbCuA6Yruzocn6eVPuMdE2e2RlVwTmo+ZRWOIcj/f+UoWfxJYRRGQ="
  email: false
dist: trusty
language: node_js
node_js:
  - '4'
env:
  secure: "dJffN9tTNflPlbKfcbzXLNsmul0Im30qiH3jgmXsBOumnqwd6GZS4Aua3Ms0Xj6V3ISpRnDxMZX0y/jXUxRGtYr3d12+vM/pBIEonNFh69KgMhtl2MfKm5ETAL3mSfUJb+hOLYy8TJBDSQ1dXJaGFgvUE1ZMwQnjxBu2NbMNjnEL9UFXHvX570OutYmyFzYL+GsMWuRfcLVrseF6mXCZdM8fDALgQrW5JX0VmAkudRmLQuUwsFVW2p2w4GIlk0spiy0OKmZWuYvfLVuZ7FfQziWFCznAlOfCzHMq3YIas0AED1ZGEfnGOAJSXe+aSx9TErGhqRIkpzqlb92A5FHHAj7InDmMRj79aDeQGDJl5ZjhtWfGdwZF5ht2Rnzlnxr0I43nRXKBhuCRvhEMi8XYwmI/YPavjAnPjaUHZwCakYR2YyLBODMUKWJy4t9ji0fYnbflU5MhlidWgdF43uthDxTKCmrWWbSkXwSTVlorgTrbyKg52QLlId/z5b6on5cs4HcBWbEDMFZ7IMhNCty+QDW2NSw/fEsmK+mgxjdcvF4lT9nCUDign+O8LpVSXQOcK5dhfsu4nLjMg8Y26L5r9+EUc6nM9N7q0j3ST3juX6BHC01u7Fsfc5sUe5xpIvZAnXst9RiznxMDwj3Z8mOgzapEs/eWAZV1/HleyGN2mro="
cache:
  directories:
    - "$HOME/.npm"
    - "$HOME/.cache"
addons:
  firefox: 49.0
before_install:
  - npm config set spin false
  - npm install -g bower
  - bower --version
install:
  - npm install
  - bower install
before_script:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - sleep 3
script:
  - npm test
deploy:
  - provider: script
    script: ember deploy staging --activate=true
    skip_cleanup: true
    on:
      branch: develop
  - provider: script
    script: ember deploy production --activate=true
    skip_cleanup: true
    on:
      branch: master
