---
AWSTemplateFormatVersion: 2010-09-09
Description: >
  This template creates the S3 buckets used to host the staging/production
  versions of the home Ember app.

Parameters:
  DomainName:
    Description: Naked Domain, this needs to be verified on Route 53 first.
    Type: String
    Default: theapothecaryshoppe.com

  DasherizedName:
    Description: Dasherized name to prefix S3 buckets with
    Type: String
    Default: the-apothecary-shoppe

Resources:
  StagingSSLCertificate: 
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub staging.${DomainName}

  ProductionSSLCertificate: 
    Type: AWS::CertificateManager::Certificate
    Properties:
      DomainName: !Sub www.${DomainName}

  CIUser:
    Type: AWS::IAM::User
    Properties:
      UserName: ci-home-web
      Policies:
        - PolicyName: ci-home-web
          PolicyDocument:
            Version: 2012-10-17
            Statement:
              - Effect: Allow
                Action:
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${DasherizedName}-home-web-staging
                  - !Sub arn:aws:s3:::${DasherizedName}-home-web-production
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:PutObject
                  - s3:PutObjectAcl
                Resource:
                  - !Sub arn:aws:s3:::${DasherizedName}-home-web-staging/*
                  - !Sub arn:aws:s3:::${DasherizedName}-home-web-production/*

  NakedDomainS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Ref DomainName
      WebsiteConfiguration:
        RedirectAllRequestsTo:
          HostName: !Sub www.${DomainName}
          Protocol: https

  NakedDomainApexRecord:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      Comment: Zone apex alias target at naked domain s3 bucket
      RecordSets:
        - Name: !Sub ${DomainName}.
          Type: A
          AliasTarget:
            DNSName: !Sub s3-website-${AWS::Region}.amazonaws.com
            # Name of Hosted Zone ID for us-east-1 from
            # http://docs.aws.amazon.com/general/latest/gr/rande.html#s3_website_region_endpoints
            HostedZoneId: Z3AQBSTGFYJSTF

  StagingS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub ${DasherizedName}-home-web-staging
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  ProductionS3Bucket:
    Type: AWS::S3::Bucket
    Properties:
      AccessControl: PublicRead
      BucketName: !Sub ${DasherizedName}-home-web-production
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html

  StagingCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub staging.${DomainName}
        Comment: !Sub staging.${DomainName}
        Origins:
        - DomainName: !Sub ${StagingS3Bucket}.s3-website-${AWS::Region}.amazonaws.com
          Id: s3origin
          CustomOriginConfig:
            OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref StagingSSLCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1

  ProductionCDN:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        Aliases:
          - !Sub www.${DomainName}
        Comment: !Sub www.${DomainName}
        Origins:
          - DomainName: !Sub ${ProductionS3Bucket}.s3-website-${AWS::Region}.amazonaws.com
            Id: s3origin
            CustomOriginConfig:
              OriginProtocolPolicy: http-only
        DefaultCacheBehavior:
          AllowedMethods:
            - HEAD
            - GET
          ForwardedValues:
            QueryString: false
            Cookies:
              Forward: none
          TargetOriginId: s3origin
          ViewerProtocolPolicy: redirect-to-https
        Enabled: true
        PriceClass: PriceClass_All
        ViewerCertificate:
          AcmCertificateArn: !Ref ProductionSSLCertificate
          SslSupportMethod: sni-only
          MinimumProtocolVersion: TLSv1

  StagingRoute53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      RecordSets:
      - Name: !Sub staging.${DomainName}
        Type: A
        AliasTarget:
          # Magic AWS number:  For CloudFront, it's Z2FDTNDATAQYW2.
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt StagingCDN.DomainName

  ProductionRoute53Record:
    Type: AWS::Route53::RecordSetGroup
    Properties:
      HostedZoneName: !Sub ${DomainName}.
      RecordSets:
      - Name: !Sub www.${DomainName}
        Type: A
        AliasTarget:
          # Magic AWS number:  For CloudFront, it's Z2FDTNDATAQYW2.
          HostedZoneId: Z2FDTNDATAQYW2
          DNSName: !GetAtt ProductionCDN.DomainName

Outputs:
  CIUser:
    Description: ARN of ci-home-web IAM user
    Value: !GetAtt CIUser.Arn
